src/ikari/banks/urls.py
from django.conf.urls import url
from banks import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='bank_list'),
    url(r'^add/$', views.bank_add, name='bank_add'),
    url(r'^edit/(?P<bank_id>\d+)/$', views.bank_edit, name='bank_edit'),
    url(r'^delete/(?P<bank_id>.*)/$', views.bank_delete, name='bank_delete'),
    url(r'^list/paging$', views.Bank__asJson, name='Bank__asJson'),
    url(r'^account_list/$', views.AccountList__asJson, name='Bank__AccountList__asJson'),
    url(r'^load_account/$', views.load_account, name='load_account'),
]

src/ikari/taxes/urls.py
from django.conf.urls import url
from taxes import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='tax_list'),
    url(r'^acc_tax_list/$', views.acc_tax_list, name='acc_tax_list'),
    url(r'^add/(?P<module_type>.*)/$', views.tax_add, name='tax_add'),
    url(r'^edit/(?P<tax_id>.*)/(?P<module_type>.*)/$', views.tax_edit, name='tax_edit'),
    # url(r'^delete/(?P<tax_id>\d+)/$', views.tax_delete, name='tax_delete'),
    url(r'^delete/(?P<tax_id>.*)/(?P<module_type>.*)/$', views.tax_delete, name='tax_delete'),
    url(r'^list/pagination$', views.TaxList__asJson, name='TaxList__asJson'),
    url(r'^tax_authority_list/$', views.tax_authority_list, name='tax_authority_list'),
    url(r'^tax_authority_list/pagination$', views.TaxAuthorityList__asJson, name='TaxAuthorityList__asJson'),
    url(r'^tax_authority_add/$', views.tax_authority_add, name='tax_authority_add'),
    url(r'^tax_authority_edit/(?P<tax_authority_id>.*)/$', views.tax_authority_edit, name='tax_authority_edit'),
    url(r'^tax_authority_delete/(?P<tax_authority_id>.*)/$', views.tax_authority_delete, name='tax_authority_delete'),
    url(r'^tax_group_list/$', views.tax_group_list, name='tax_group_list'),
    url(r'^tax_group_list/pagination$', views.TaxGroupList__asJson, name='TaxGroupList__asJson'),
    url(r'^tax_group_add/$', views.tax_group_add, name='tax_group_add'),
    url(r'^tax_group_edit/(?P<tax_group_id>.*)/$', views.tax_group_edit, name='tax_group_edit'),
    url(r'^tax_group_delete/(?P<tax_group_id>.*)/$', views.tax_group_delete, name='tax_group_delete'),
]

src/ikari/taxes/models.py
from datetime import date

from django.db import models

from accounts.models import Account
from companies.models import Company
from currencies.models import Currency
from utilities.constants import RETAINAGE_REPORT_TYPES, TAX_BASE_TYPES, TAX_REPORT_LEVEL, TAX_TRX_TYPES, \
    TAX_CALCULATION_METHOD, TAX_TYPE_DICT


# Create your models here.
class Tax(models.Model):
    code = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=100, null=True)
    rate = models.DecimalField(max_digits=20, decimal_places=6, null=True)
    number = models.IntegerField(null=True)  # tax_classes
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()
    shortname = models.CharField(max_length=30, null=True)

    # additional fields from the old system
    tax_type = models.IntegerField(default=int(TAX_TYPE_DICT['Customer/Vendor']))  # 1=Customers/Vendors; 2=Items
    tax_account_code = models.ForeignKey('accounts.Account', related_name='tax_account_code',
                                         on_delete=models.CASCADE, null=True)
    distribution_code = models.ForeignKey('accounts.DistributionCode', related_name='distribution_code',
                                          on_delete=models.CASCADE, null=True)
    ytd = models.DecimalField(max_digits=20, null=True, decimal_places=6)
    mtd = models.DecimalField(max_digits=20, null=True, decimal_places=6)
    ytdoc = models.DecimalField(max_digits=20, null=True, decimal_places=6)
    mtdoc = models.DecimalField(max_digits=20, null=True, decimal_places=6)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    tax_authority = models.ForeignKey("taxes.TaxAuthority", on_delete=models.CASCADE, null=True)
    tax_group = models.ForeignKey("taxes.TaxGroup", on_delete=models.CASCADE, null=True)
    # end additional field from the old system


class TaxAuthority(models.Model):
    code = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=100, null=True)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True)
    retainage_rpt_type = models.CharField(max_length=50, null=True, choices=RETAINAGE_REPORT_TYPES)
    max_tax_allowable = models.DecimalField(max_digits=20, decimal_places=6, default=0)
    no_tax_charged_below = models.DecimalField(max_digits=20, decimal_places=6, default=0)
    tax_base = models.CharField(max_length=50, null=True, choices=TAX_BASE_TYPES)
    report_level = models.CharField(max_length=50, null=True, choices=TAX_REPORT_LEVEL)
    liability_account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True,
                                          related_name='liability_account')
    is_recoverable = models.BooleanField(default=False)
    recoverable_account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True,
                                            related_name='recoverable_account')
    recoverable_rate = models.DecimalField(max_digits=20, decimal_places=6, default=0)
    is_expense_separately = models.BooleanField(default=False)
    expense_account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True,
                                        related_name='expense_account')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()


class TaxGroup(models.Model):
    code = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=100, null=True)
    transaction_type = models.CharField(max_length=50, null=True, choices=TAX_TRX_TYPES)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True)
    calculation_method = models.CharField(max_length=50, null=True, choices=TAX_CALCULATION_METHOD)
    tax_authority = models.ForeignKey(TaxAuthority, on_delete=models.CASCADE, null=True, blank=True,
                                      related_name='tax_authority')
    is_taxable = models.BooleanField(default=False)
    is_surtax = models.BooleanField(default=False)
    surtax_authority = models.ForeignKey(TaxAuthority, on_delete=models.CASCADE, null=True, blank=True,
                                         related_name='surtax_authority')
    surtax_authority_account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()

src/ikari/taxes/views.py
import datetime
import json
import logging
import traceback

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponsePermanentRedirect, HttpResponse
from django.shortcuts import render_to_response, render
from django.template import RequestContext

from accounts.models import Account, DistributionCode
from taxes.forms import TaxForm, TaxAuthorityForm, TaxGroupForm
from taxes.models import Tax, TaxAuthority, TaxGroup
from utilities.constants import TAX_TRX_TYPES, TAX_TYPE_DICT, PAGE_TYPE, TAX_CLASS
from utilities.messages import MESSAGE_ERROR, EXCEPTION_JOURNAL_ADD, EXCEPTION_JOURNAL_EDIT, EXCEPTION_JOURNAL_DELETE, \
    INVALID_FORM

logger = logging.getLogger(__name__)


# Create your views here.
@login_required
def load_list(request):
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    tax_list = Tax.objects.filter(is_hidden=0, company_id=company_id)
    return render_to_response('tax-list.html', RequestContext(request, {'tax_list': tax_list}))


@login_required
def acc_tax_list(request):
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    tax_list = Tax.objects.filter(is_hidden=0, company_id=company_id)
    return render_to_response('acc-tax-list.html', RequestContext(request, {'tax_list': tax_list}))


@login_required
@permission_required('taxes.add_tax', login_url='/alert/')
def tax_add(request, module_type):
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    dis_code_list = DistributionCode.objects.filter(is_hidden=False, is_active=True, company_id=company_id)
    tax_group = []#TaxGroup.objects.filter(is_hidden=0, company_id=company_id)
    tax_authority = TaxAuthority.objects.filter(is_hidden=0, company_id=company_id)
    if request.method == 'POST':
        form = TaxForm(company_id, request.POST)
        keys = ['name', 'rate', 'code', 'number', 'ytd', 'mtd', 'ytdoc', 'mtdoc', 'tax_type', 'shortname',
                'tax_group_id']
        tax = Tax()

        for key in keys:
            if request.POST.get(key):
                setattr(tax, key, request.POST.get(key))

        try:
            if request.POST.get('tax_account_code'):
                tax.tax_account_code_id = request.POST.get('tax_account_code')
            else:
                tax.tax_account_code_id = None
            if request.POST.get('distribution_code'):
                tax.distribution_code_id = request.POST.get('distribution_code')
            else:
                tax.distribution_code_id = None
            tax.create_date = datetime.datetime.today()
            tax.update_date = datetime.datetime.today()
            tax.update_by = request.user.id
            tax.is_hidden = 0
            tax.company_id = company_id
            tax.save()
        except OSError as e:
            messages.add_message(request, messages.ERROR, e, extra_tags='tax_add')

        if int(module_type) == int(PAGE_TYPE['S&P']):
            return HttpResponsePermanentRedirect(reverse('tax_list'))
        else:
            return HttpResponsePermanentRedirect(reverse('acc_tax_list'))

    else:
        form = TaxForm(company_id)
    return render(request, 'tax-form.html' if int(module_type) == int(PAGE_TYPE['S&P']) else 'acc-tax-form.html',
                  {'form': form, 'dis_code_list': dis_code_list, 'tax_group_list': tax_group,
                   'tax_authority_list': tax_authority})


@login_required
@permission_required('taxes.change_tax', login_url='/alert/')
def tax_edit(request, tax_id, module_type):
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    tax = Tax.objects.get(pk=tax_id)
    dis_code_list = DistributionCode.objects.filter(is_hidden=False, is_active=True, company_id=company_id)
    tax_group = []#TaxGroup.objects.filter(is_hidden=0, company_id=company_id)
    tax_authority = TaxAuthority.objects.filter(is_hidden=0, company_id=company_id)
    if request.method == 'POST':
        try:
            if request.POST.get('number'):
                tax.number = request.POST.get('number')
            else:
                tax.number = None
            if request.POST.get('code'):
                tax.code = request.POST.get('code')
            else:
                tax.code = None
            if request.POST.get('name'):
                tax.name = request.POST.get('name')
            else:
                tax.name = None
            if request.POST.get('rate'):
                tax.rate = request.POST.get('rate')
            else:
                tax.rate = None
            if request.POST.get('shortname'):
                tax.shortname = request.POST.get('shortname')
            else:
                tax.shortname = None

            # additional fields from the old system
            if request.POST.get('tax_type'):
                tax.tax_type = request.POST.get('tax_type')
            else:
                tax.tax_type = None

            if request.POST.get('tax_group'):
                tax.tax_group_id = int(request.POST.get('tax_group'))
            else:
                tax.tax_group_id = None

            if request.POST.get('tax_account_code'):
                tax.tax_account_code_id = request.POST.get('tax_account_code')
            else:
                tax.tax_account_code_id = None
            if request.POST.get('distribution_code'):
                tax.distribution_code_id = request.POST.get('distribution_code')
            else:
                tax.distribution_code_id = None

            if request.POST.get('mtd'):
                tax.mtd = request.POST.get('mtd')
            else:
                tax.mtd = None
            if request.POST.get('ytd'):
                tax.ytd = request.POST.get('ytd')
            else:
                tax.ytd = None
            if request.POST.get('mtdoc'):
                tax.mtdoc = request.POST.get('mtdoc')
            else:
                tax.mtdoc = None
            if request.POST.get('ytdoc'):
                tax.ytdoc = request.POST.get('ytdoc')
            else:
                tax.ytdoc = None
            # end of additional fields

            tax.update_date = datetime.datetime.today()
            tax.update_by = request.user.id
            tax.save()
        except OSError as e:
            messages.add_message(request, messages.ERROR, e, extra_tags='tax_edit')
        if int(module_type) == int(PAGE_TYPE['S&P']):
            return HttpResponsePermanentRedirect(reverse('tax_list'))
        else:
            return HttpResponsePermanentRedirect(reverse('acc_tax_list'))

    tax.update_date = tax.update_date.strftime("%d-%m-%Y")
    form = TaxForm(company_id, instance=tax)
    if int(module_type) == int(PAGE_TYPE['S&P']):
        return render(request, 'tax-form.html',
                      {'form': form, 'tax': tax, 'dis_code_list': dis_code_list, 'tax_group_list': tax_group,
                       'tax_authority_list': tax_authority})
    else:
        return render(request, 'acc-tax-form.html',
                      {'form': form, 'tax': tax, 'dis_code_list': dis_code_list, 'tax_group_list': tax_group,
                       'tax_authority_list': tax_authority})


@login_required
@permission_required('taxes.delete_tax', login_url='/alert/')
def tax_delete(request, tax_id, module_type):
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    if request.method == 'POST':
        try:
            tax = Tax.objects.get(pk=tax_id)
            tax.is_hidden = True
            tax.save()
        except OSError as e:
            messages.add_message(request, messages.ERROR, e, extra_tags='tax_delete')
        if int(module_type) == int(PAGE_TYPE['S&P']):
            return HttpResponsePermanentRedirect(reverse('tax_list'))
        else:
            return HttpResponsePermanentRedirect(reverse('acc_tax_list'))


@login_required
def TaxList__asJson(request):
    draw = request.GET['draw']
    start = request.GET['start']
    length = request.GET['length']
    search = request.GET['search[value]']
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    tax_list = Tax.objects.filter(is_hidden=0, company_id=company_id)
    records_total = tax_list.count()

    if search:  # Filter data base on search
        tax_list = tax_list.filter(
            Q(name__icontains=search) |
            Q(code__icontains=search) |
            Q(rate__contains=search) |
            Q(tax_account_code__name__icontains=search) |
            Q(distribution_code__name__icontains=search) |
            Q(update_date__contains=search))

    # All data
    records_filtered = tax_list.count()

    # Order by list_limit base on order_dir and order_column
    order_column = request.GET['order[0][column]']
    if order_column == "0":
        column_name = "update_date"
    elif order_column == "1":
        column_name = "code"
    elif order_column == "2":
        column_name = "name"
    elif order_column == "3":
        column_name = "rate"
    elif order_column == "4":
        column_name = "tax_account_code__name"
    elif order_column == "5":
        column_name = "distribution_code__name"

    order_dir = request.GET['order[0][dir]']
    if order_dir == "asc":
        list = tax_list.order_by(column_name)[int(start):(int(start) + int(length))]
    if order_dir == "desc":
        list = tax_list.order_by('-' + column_name)[int(start):(int(start) + int(length))]

    # Create data list
    array = []
    for field in list:
        data = {"id": field.id,
                "update_date": field.update_date.strftime("%d-%m-%Y"),
                "shortname": field.shortname,

src/ikari/taxes/templates/tax-add.html
{% extends "base.html" %}

{% block extrahead %}
    {% load staticfiles %}
{% endblock %}

{% block title %}Add Tax{% endblock %}
{% block tax_active %}active{% endblock %}
{% block sp_setting_a_active %}active{% endblock %}
{% block sp_setting_i_active %}active{% endblock %}
{% block parent_order_a_active %}active{% endblock %}
{% block parent_order_i_active %}active{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Add Tax
            </header>
            <div class="panel-body">
                <form class="form-horizontal" action="{% url 'tax_add' %}" role="form" method="post" onsubmit="return checkForm(this);"
                      enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="name" class="col-lg-2 col-sm-2 control-label">Name<span
                                class="span-required">(*)</span></label>
                        <div class="col-lg-8">
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="rate" class="col-lg-2 col-sm-2 control-label">Rate<span
                                class="span-required">(*)</span></label>
                        <div class="col-lg-8">
                            <input type="text" class="form-control" id="rate" name="rate" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="number" class="col-lg-2 col-sm-2 control-label">Number</label>
                        <div class="col-lg-8">
                            <input type="number" class="form-control" id="number" name="number">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button type="submit" name="btnSave" class="btn btn-success">Save</button>
                            <a class="btn btn-default" href="{% url 'tax_list' %}">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </section>
    </div>
{% endblock %}

{% block extrafoot %}
    {% load staticfiles %}
    <script type="application/javascript" src="{% static 'js/ga.js' %}"></script>
{% endblock %}

src/ikari/taxes/templates/tax-group-form.html
{% extends "base.html" %}

{% block extrahead %}
    {% load staticfiles %}
    <link href="{% static "css/select2/select2.css" %}" rel="stylesheet">
    <style>
        .text-right { text-align: right; }
    </style>
{% endblock %}

{% block title %}{% if tax_group.id == None %}
    Add Tax Group{% else %} Edit Tax Group
{% endif %}{% endblock %}
{% block parent_accounting_a_active %}active{% endblock %}
{% block parent_accounting_i_active %}active{% endblock %}
{% block com_tax_services_a_active %}active{% endblock %}
{% block com_tax_services_i_active %}active{% endblock %}
{% block com_tax_group_active %}active{% endblock %}

{% block content %}
<div class="col-lg-12">
    <section class="panel">
        <header class="panel-heading">
            {% if tax_group.id == None %}
                Add Tax Group{% else %} Edit Tax Group
            {% endif %}
        </header>
        <div class="panel-body">
            <form id="frmTaxGroup" class="form-horizontal"
                    {% if tax_group.id == None %} action="{% url 'tax_group_add' %}"
                    {% else %} action="{% url 'tax_group_edit' tax_group.id %}" {% endif %}
                  role="form" method="POST" onsubmit="return checkForm(this);" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="code" class="col-lg-2 col-sm-2 control-label">Tax Group<span class="span-required"> (*)</span></label>
                    <div class="col-lg-6">
                        {{ form.code }}
                        <span class="messages">{{ form.errors.code }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="name" class="col-lg-2 col-sm-2 control-label">Description</label>
                    <div class="col-lg-6">
                        {{ form.name }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="transaction_type" class="col-lg-2 col-sm-2 control-label">Transaction Type</label>
                    <div class="col-lg-6">
                        {{ form.transaction_type }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="currency" class="col-lg-2 col-sm-2 control-label">Tax Reporting Currency<span class="span-required"> (*)</span></label>
                    <div class="col-lg-6">
                        {{ form.currency }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="calculation_method" class="col-lg-2 col-sm-2 control-label">Tax Calculation Method</label>
                    <div class="col-lg-6">
                        {{ form.calculation_method }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="tax_authority" class="col-lg-2 col-sm-2 control-label">Tax Authority</label>
                    <div class="col-lg-6">
                        <select id="tax_authority" class="form-control" name="tax_authority">
                            <option value=""></option>
                            {% for tx_auth in tax_authority_list %}
                                {% if tax_group.tax_authority_id == tx_auth.id %}
                                    <option value="{{tx_auth.id}}" selected="selected">{{tx_auth.code}}</option>
                                {% else %}
                                    <option value="{{tx_auth.id}}">{{tx_auth.code}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label">Taxable</label>
                    <div class="col-lg-6">
                        <div class="checkbox checkbox-primary">
                            <input name="is_taxable" id="is_taxable" class="styled" type="checkbox"
                                   {% if tax_group.is_taxable %}checked{% endif %}/>
                            <label for="is_taxable"></label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label">Surtax</label>
                    <div class="col-lg-6">
                        <div class="checkbox checkbox-primary">
                            <input name="is_surtax" id="is_surtax" class="styled" type="checkbox"
                                   {% if tax_group.is_surtax %}checked{% endif %}/>
                            <label for="is_surtax"></label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="surtax_on_authority" class="col-lg-2 col-sm-2 control-label">Surtax on Authority</label>
                    <div class="col-lg-6">
                        <select id="surtax_on_authority" class="form-control" name="surtax_on_authority">
                            <option value=""></option>
                            {% for tx_auth in tax_authority_list %}
                                {% if tax_group.surtax_authority_id == tx_auth.id %}
                                    <option value="{{tx_auth.id}}" selected="selected">{{tx_auth.code}}</option>
                                {% else %}
                                    <option value="{{tx_auth.id}}">{{tx_auth.code}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-group "></div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button id="btnSave" type="submit" name="btnSave" class="btn btn-primary">Save</button>
                        <a href="#delete-dialog" data-toggle="modal" class="btn btn-danger" {% if tax_group.id == None %}style="display: none"{% endif %}>Delete</a>
                        <a class="btn btn-default" href="{% url 'tax_group_list' %}">Cancel</a>
                    </div>
                </div>

            </form>
        </div>
        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="delete-dialog"
             class="modal fade">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                        <h4 class="modal-title">Delete Confirm Dialog</h4>
                    </div>
                    <div class="modal-body">
                        <form role="form" action="{% url 'tax_group_delete' tax_group.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Are you sure want to delete?</label>
                            </div>
                            <button type="submit" class="btn btn-primary">OK</button>
                            <button class="btn btn-default" type="button" 
                                data-dismiss="modal" style="margin-left:5px">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>

{#notification#}
<div class="modal fade" id="notificationModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><strong><span id='notificationModal_title'>Notification Title</span></strong></h4>
            </div>
            <div class="modal-body" style="padding-bottom: 0px!important;">
                <div class="form-group">
                    <div id="notificationModal_text1" class="text-left">Notification #1</div>
                    <div id="notificationModal_text2" class="text-left">Notification #2</div>
                </div>
            </div>
            <div class="modal-footer" style="text-align: center">
                <button id="notification_ok" class="btn btn-primary" type="button" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
{#End notification#}

{% endblock %}

{% block extrafoot %}
    {% load staticfiles %}
    <script type="application/javascript" src="{% static 'js/ga.js' %}"></script>
    <script src="{% static "js/select2/select2.js" %}"></script>

    <script>
        $(document).ready(function () {
            if($('#is_surtax').is(':checked')){
                $('#surtax_on_authority').prop('disabled', false);
                $('#surtax_account').prop('disabled', false);
            } else {
                $('#surtax_on_authority').prop('disabled', true);
                $('#surtax_account').prop('disabled', true);
            }

            $('#id_currency').select2({
                placeholder: "select currency ",
            });
            $('#id_transaction_type').select2();
            $('#id_calculation_method').select2();
            $('#tax_authority').select2({
                placeholder: "select tax authority",
            });
            $('#surtax_on_authority').select2({
                placeholder: "select surtax on authority",
            });
        });

        $('#is_surtax').on('change',function(){
            if($(this).is(':checked')){
                $(this).attr('checked', 'checked');
                $('#surtax_on_authority').prop('disabled', false);
            } else {
                $(this).removeAttr('checked');
                $('#surtax_on_authority').val('').trigger('change');
                $('#surtax_on_authority').prop('disabled', true);
            }
        });

        $('#btnSave').on('click',function(){
            var is_surtax = $('#is_surtax').is(':checked');
            var code = $('#id_code').val()
            var curr = $('#id_currency').val()
            if ((!code)||(!curr)) {
                $('#notificationModal_title').text('Invalid Input !');
                $('#notificationModal_text1').text('Tax Group and Tax Reporting Currency cannot be empty. Field with (*) marks is required.');
                $('#notificationModal_text2').text('');
                $("#notificationModal").modal("show");
                return false;
            //} else if ((is_surtax)&&((!$('#surtax_on_authority').val())||(!$('#surtax_account').val()))){
            } else if ((is_surtax)&&((!$('#surtax_on_authority').val()))){
                $('#notificationModal_title').text('Invalid Input !');
                $('#notificationModal_text1').text('Surtax on Authority and Surtax Authority cannot be empty.');
                $('#notificationModal_text2').text('If you want to leave it empty, make sure to uncheck Surtax checkbox.');
                $("#notificationModal").modal("show");
                return false;
            } else {
                $('#frmTaxGroup').submit();
            }
        });
    </script>
{% endblock %}