src/ikari/banks/urls.py
from django.conf.urls import url
from banks import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='bank_list'),
    url(r'^add/$', views.bank_add, name='bank_add'),
    url(r'^edit/(?P<bank_id>\d+)/$', views.bank_edit, name='bank_edit'),
    url(r'^delete/(?P<bank_id>.*)/$', views.bank_delete, name='bank_delete'),
    url(r'^list/paging$', views.Bank__asJson, name='Bank__asJson'),
    url(r'^account_list/$', views.AccountList__asJson, name='Bank__AccountList__asJson'),
    url(r'^load_account/$', views.load_account, name='load_account'),
]

src/ikari/transactions/urls.py
from django.conf.urls import url
from transactions import views

urlpatterns = [
    url(r'^$', views.trans_method_list, name='index'),
    url(r'^method/list/$', views.trans_method_list, name='trans_method_list'),
    url(r'^method/all/$', views.trans_mode, name='trans_mode'),
    url(r'^method/add/(?P<menu_type>.*)/$', views.trans_method_add, name='trans_method_add'),
    url(r'^method/edit/(?P<trans_method_id>.*)/(?P<menu_type>.*)/$', views.trans_method_edit, name='trans_method_edit'),
    url(r'^method/delete/(?P<trans_method_id>\d+)/$', views.trans_method_delete, name='trans_method_delete'),

    url(r'^get-info-transaction/$', views.get_info_transaction, name='get_info_transaction'),
    url(r'^get-gl-info-transaction/$', views.get_gl_info_transaction, name='get_gl_info_transaction'),
    
    url(r'^list/pagination$', views.TransMethod__asJson, name='TransMethod__asJson'),
]

src/ikari/transactions/models.py
from django.db import models
from companies.models import Company
from accounts.models import Account, DistributionCode
from currencies.models import Currency
from taxes.models import Tax
from datetime import date
from utilities.constants import SOURCE_TYPES, BALANCE_TYPE


# Create your models here.
class TransactionMethod(models.Model):
    name = models.CharField(max_length=100, null=True)
    code = models.CharField(max_length=10, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    is_debit = models.BooleanField(default=True)
    is_credit = models.BooleanField(default=True)
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()


# Create your models here.
class Transaction(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    order = models.ForeignKey("orders.Order", on_delete=models.CASCADE, null=True)
    journal = models.ForeignKey("accounting.Journal", on_delete=models.CASCADE, null=True, related_name='journal', db_index=True)
    is_credit_account = models.BooleanField(default=False)
    is_debit_account = models.BooleanField(default=False)
    pair = models.ForeignKey('self', null=True, blank=True, related_name='pair_transactions')
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True)
    tax = models.ForeignKey(Tax, on_delete=models.CASCADE, null=True)
    distribution_code = models.ForeignKey(DistributionCode, on_delete=models.CASCADE, null=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=20, decimal_places=6, default=0)  # Amount before tax
    discount_amount = models.DecimalField(max_digits=20, decimal_places=6, default=0)  # Amount discount
    adjustment_amount = models.DecimalField(max_digits=20, decimal_places=6, default=0)  # Amount adjustment (+/-)
    base_tax_amount = models.DecimalField(max_digits=20, decimal_places=6, default=0, null=True)
    tax_amount = models.DecimalField(max_digits=20, decimal_places=6, default=0)
    total_amount = models.DecimalField(max_digits=20, decimal_places=6, default=0)  # Amount - discount - (+adjustment) after tax
    transaction_date = models.DateField(default=date.today)
    remark = models.TextField(max_length=100, null=True, default='')
    method = models.ForeignKey(TransactionMethod, on_delete=models.CASCADE, null=True)
    number = models.CharField(max_length=50, null=True, default='')
    # GL Entry
    source_type = models.CharField(max_length=50, null=True, choices=SOURCE_TYPES)  # ==> Use For 5: GL
    reference = models.CharField(max_length=100, null=True, default='')
    description = models.CharField(max_length=500, null=True, default='')
    functional_currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True, related_name='functional_currency')
    functional_amount = models.DecimalField(max_digits=20, decimal_places=6, default=0)  # Amount before tax
    rate_date = models.DateField(null=True)
    exchange_rate = models.DecimalField(max_digits=20, decimal_places=10, default=1)
    # create this field for Payment/Receipt, not sure if necessary in future
    related_invoice = models.ForeignKey("accounting.Journal", on_delete=models.CASCADE, null=True, related_name='related_invoice', db_index=True)
    # End GL Entry
    is_tax_include = models.BooleanField(default=False)
    is_tax_transaction = models.BooleanField(default=False)
    is_manual_tax_input = models.BooleanField(default=False)
    is_close = models.BooleanField(default=False)
    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField(default=False)
    functional_balance_type = models.CharField(max_length=1, choices=BALANCE_TYPE, null=True)
    is_report = models.BooleanField(default=False)
    is_clear_tax = models.BooleanField(default=False)
    is_auto_exch = models.BooleanField(default=False)

    related_journal_outstanding = models.DecimalField(max_digits=20, decimal_places=6, default=0)

    def __str__(self):
        return str(self.id) + '-- Journal_ID: ' + str(self.journal_id) + ' - Related_invoice_id: ' + str(self.related_invoice_id)

src/ikari/transactions/views.py
import datetime
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponsePermanentRedirect, HttpResponse
from django.shortcuts import render_to_response, render, get_object_or_404
from django.template import RequestContext

from accounting.forms import PaymentCodeForm
from accounting.models import PaymentCode
from transactions.models import Transaction
from utilities.constants import TRN_CODE_TYPE_DICT


# Create your views here.@login_required
def trans_method_list(request):
    return render_to_response('trans-method-list.html',
                              RequestContext(request, {'menu_type': TRN_CODE_TYPE_DICT['Global']}))


@login_required
def trans_mode(request):
    return render_to_response('trans-method-list.html',
                              RequestContext(request, {'menu_type': TRN_CODE_TYPE_DICT['Sales Number File']}))


@login_required
@permission_required('transactions.add_transactionmethod', login_url='/alert/')
def trans_method_add(request, menu_type):
    company_id = request.session['login_company_id'] if request.session['login_company_id'] else 0
    if request.method == 'POST':
        form = PaymentCodeForm(request.POST)
        if form.is_valid():
            try:
                my_trans_method = form.save(commit=False)
                my_trans_method.company_id = company_id
                my_trans_method.create_date = datetime.datetime.today()
                my_trans_method.update_date = datetime.datetime.today()
                my_trans_method.update_by = request.user.id
                my_trans_method.is_hidden = 0
                my_trans_method.save()
            except OSError as e:
                messages.add_message(request, messages.ERROR, e, extra_tags='trans_method_add')
            return HttpResponsePermanentRedirect(reverse('trans_method_list'))
        else:
            form = PaymentCodeForm(request.POST)
    else:
        form = PaymentCodeForm()
    return render(request, 'trans-method-form.html', {'form': form, 'menu_type': menu_type})


@login_required
@permission_required('transactions.change_transactionmethod', login_url='/alert/')
def trans_method_edit(request, trans_method_id, menu_type):
    my_trans_method = get_object_or_404(PaymentCode, pk=trans_method_id)
    if request.method == 'POST':
        form = PaymentCodeForm(request.POST, instance=my_trans_method)
        if form.is_valid():
            try:
                my_trans_method = form.save(commit=False)
                my_trans_method.update_date = datetime.datetime.today()
                my_trans_method.update_by = request.user.id
                my_trans_method.is_hidden = 0
                my_trans_method.save()
            except OSError as e:
                messages.add_message(request, messages.ERROR, e, extra_tags='trans_method_edit')
            return HttpResponsePermanentRedirect(reverse('trans_method_list'))
    my_trans_method.update_date = my_trans_method.update_date.strftime("%d-%m-%Y")    
    form = PaymentCodeForm(instance=my_trans_method)
    return render(request, 'trans-method-form.html',
                  {'form': form, 'trans_method': my_trans_method, 'menu_type': menu_type})


@login_required
@permission_required('transactions.delete_transactionmethod', login_url='/alert/')
def trans_method_delete(request, trans_method_id):
    if request.method == 'POST':
        try:
            my_trans_method = PaymentCode.objects.get(pk=trans_method_id)
            my_trans_method.is_hidden = True
            my_trans_method.save()
            return HttpResponsePermanentRedirect(reverse('trans_method_list'))
        except OSError as e:
            messages.add_message(request, messages.ERROR, e, extra_tags='trans_method_delete')


@login_required
def TransMethod__asJson(request):
    draw = request.GET['draw']
    start = request.GET['start']
    length = request.GET['length']
    search = request.GET['search[value]']
    list_filter = PaymentCode.objects.filter(is_hidden=0)
    records_total = list_filter.count()

    if search:  # Filter data base on search
        list_filter = list_filter.filter(
            Q(name__contains=search) | Q(code__contains=search) | Q(update_date__contains=search)
        )

    # All data
    records_filtered = list_filter.count()

    # Order by list_limit base on order_dir and order_column
    order_column = request.GET['order[0][column]']
    if order_column == "0":
        column_name = "update_date"
    elif order_column == "1":
        column_name = "code"
    elif order_column == "2":
        column_name = "name"
    order_dir = request.GET['order[0][dir]']
    if order_dir == "asc":
        list = list_filter.order_by(column_name)[int(start):(int(start) + int(length))]
    if order_dir == "desc":
        list = list_filter.order_by('-' + column_name)[int(start):(int(start) + int(length))]

    # Create data list
    array = []
    for j, field in enumerate(list):
        # for field in list:
        data = {"id": field.id,
                "update_date": field.update_date.strftime("%d-%m-%Y"),
                "code": field.code,
                "name": field.name}
    array.append(data)

    content = {
        "draw": draw,
        "data": array,
        "recordsTotal": records_total,
        "recordsFiltered": records_filtered
    }

    json_content = json.dumps(content, ensure_ascii=False)
    return HttpResponse(json_content, content_type='application/json')


@login_required
def get_info_transaction(request):
    if request.method == 'POST':
        try:
            transaction_id = request.POST.get('transaction_id')
            transaction = Transaction.objects.get(id=transaction_id)
            data = {}
            if transaction.distribution_code_id:
                data["distribution_id"] = transaction.distribution_code_id
                data["distribution_code"] = transaction.distribution_code.code
                data["distribution_desc"] = transaction.distribution_code.name
            else:
                data["distribution_id"] = ""
                data["distribution_code"] = ""
                data["distribution_desc"] = ""
            data["account_id_trs"] = transaction.account_id
            data["account_code"] = transaction.account.code
            data["account_desc"] = transaction.account.name
            data["description"] = transaction.description
            data["amount"] = str(transaction.amount)
            data["base_tax_amount"] = str(transaction.base_tax_amount)
            data["tax_amount"] = str(transaction.tax_amount)
            data["total_amount"] = str(transaction.total_amount)
            data["is_tax_include"] = str(int(transaction.is_tax_include))
            data["tax_id"] = str(transaction.tax_id)
            data["is_tax_transaction"] = transaction.is_tax_transaction
            data["is_manual_tax_input"] = transaction.is_manual_tax_input

            array = []
            array.append(data)
            json_content = json.dumps(array, ensure_ascii=False)
            return HttpResponse(json_content, content_type='application/json')
        except ObjectDoesNotExist:
            messages_error = "Can't load transaction"
            return render_to_response('404.html', RequestContext(request, {'messages_error': messages_error}))


@login_required
def get_gl_info_transaction(request):
    if request.method == 'POST':
        try:
            transaction_id = request.POST.get('transaction_id')
            transaction = Transaction.objects.get(id=transaction_id)
            data = {"reference": transaction.reference,
                    "description": transaction.description,
                    "account_id": transaction.account_id,
                    "account_code": transaction.account.code,
                    "account_name": transaction.account.name,
                    "currency_id": transaction.currency_id,
                    "currency_code": transaction.currency.code,
                    "currency_name": transaction.currency.name,
                    "is_decimal": transaction.currency.is_decimal,
                    "amount": str(transaction.amount),
                    "exchange_rate": str(transaction.exchange_rate),
                    "rate_date": transaction.rate_date.strftime("%d-%m-%Y") if transaction.rate_date else '',
                    "functional_amount": str(transaction.functional_amount),
                    "remark": transaction.remark,
                    "is_debit_account": transaction.is_debit_account,
                    "functional_balance_type": transaction.functional_balance_type,
                    "is_auto_exch": transaction.is_auto_exch}
            array = []
            array.append(data)
            json_content = json.dumps(array, ensure_ascii=False)
            return HttpResponse(json_content, content_type='application/json')
        except ObjectDoesNotExist:
            messages_error = "Can't load transaction"
            return render_to_response('404.html', RequestContext(request, {'messages_error': messages_error}))

src/ikari/transactions/templates/trans-method-form.html
{% extends "base.html" %}

{% block extrahead %}
    {% load staticfiles %}
{% endblock %}

{% block title %}Payment Mode{% endblock %}

{% block trans_method_active %}
{% if menu_type == '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
    active
{% endif %}
{% endblock %}

{% block parent_system_setting_a_active %}
{% if menu_type == '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
    active
{% endif %}
{% endblock %}

{% block parent_system_setting_i_active %}
{% if menu_type == '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
    active
{% endif %}
{% endblock %}

{% block parent_order_a_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block parent_order_i_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block code_sp_a_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block code_sp_i_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block payment_mode_sp_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Payment Mode
            </header>
            <div class="panel-body">
                <form class="form-horizontal"
                        {% if trans_method.id %}
                      action="{% url 'trans_method_edit' trans_method.id menu_type %}"
                        {% else %}
                      action="{% url 'trans_method_add' menu_type %}"
                        {% endif %}
                      role="form" method="post" onsubmit="return checkForm(this);" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="code" class="col-lg-2 col-sm-2 control-label">Code Type</label>
                        <div class="col-lg-6">
                           <select class="form-control" >
                           <option>Payment Mode</option>
                           </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="rate" class="col-lg-2 col-sm-2 control-label">Code<span
                                class="span-required">(*)</span></label>
                        <div class="col-lg-6">
                            {{ form.code }}
                            <span class="messages">{{ form.errors.code }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-lg-2 col-sm-2 control-label">Name<span
                                class="span-required">(*)</span></label>
                        <div class="col-lg-6">
                            {{ form.name }}
                            <span class="messages">{{ form.errors.name }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label">Last Update</label>
                        <div class="col-lg-6">
                            {{ form.update_date }}
                        </div>
                    </div>
                    <!-- <div class="form-group">
                        <label for="label_check" class="col-lg-2 col-sm-2 control-label"></label>
                        <div class="col-lg-2">
                            <div class="checkbox checkbox-primary">
                                {{ form.is_debit }}
                                <label for="id_is_debit">
                                    Debit
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="checkbox checkbox-primary">
                                {{ form.is_credit }}
                                <label for="id_is_credit">
                                    Credit
                                </label>
                            </div>
                        </div>
                    </div> -->
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button type="submit" name="btnSave" class="btn btn-success">Save</button>
                            {% if 'transactions.delete_transactionmethod' in user.get_all_permissions and trans_method.id %}
                                <a href="#delete-dialog" data-toggle="modal" class="btn btn-danger">Delete</a>
                            {% endif %}

                            {% if menu_type = '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
                            <a class="btn btn-default" href="{% url 'trans_method_list' %}">
                            {% else %}
                            <a class="btn btn-default" href="{% url 'trans_mode' %}">
                            {% endif %}
                            Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
            {% if trans_method.id %}
                <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="delete-dialog"
                     class="modal fade">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                                <h4 class="modal-title">Delete Confirm Dialog</h4>
                            </div>
                            <div class="modal-body">
                                <form role="form" action="{% url 'trans_method_delete' trans_method.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Are you sure want to delete?</label>
                                    </div>
                                    <button type="submit" class="btn btn-success">OK</button>
                                    <a class="btn btn-default" href="{% url 'trans_method_edit' trans_method.id menu_type %}">Cancel</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </section>
    </div>
{% endblock %}

{% block extrafoot %}
    {% load staticfiles %}
{% endblock %}

src/ikari/transactions/templates/trans-method-list.html
{% extends "base.html" %}

<!--dynamic table-->
{% block extrahead %}
    {% load staticfiles %}
{% endblock %}

{% block title %}Payment Mode List{% endblock %}

{% block trans_method_active %}
{% if menu_type == '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
    active
{% endif %}
{% endblock %}

{% block parent_system_setting_a_active %}
{% if menu_type == '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
    active
{% endif %}
{% endblock %}

{% block parent_system_setting_i_active %}
{% if menu_type == '0' %} {# TRN_CODE_TYPE_DICT['Global'] #}
    active
{% endif %}
{% endblock %}

{% block parent_order_a_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block parent_order_i_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block code_sp_a_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block code_sp_i_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block payment_mode_sp_active %}
{% if menu_type == '2'%} {# TRN_CODE_TYPE_DICT['Sales Number File'] #}
    active
{% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading" style="font-size: 20px">
                    Payment Mode List
                    <span class="tools pull-right">
                         {% if 'transactions.add_transactionmethod' in user.get_all_permissions %}
                             <a class="btn btn-success start" href="{% url 'trans_method_add' menu_type %}">
                                 <i class="glyphicon glyphicon-plus"></i>
                                 <span>Add new</span>
                             </a>
                         {% endif %}
                    </span>
                </header>
                <div class="panel-body">
                    <div class="adv-table">
                        <table class="display table table-bordered table-striped" id="dynamic-table" style="width:100%">
                            <thead>
                            <tr>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Last Update</th>
                                {% if 'transactions.change_transactionmethod' in user.get_all_permissions %}
                                    <th class="text-center">Edit</th>
                                {% endif %}
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}
{% block js %}
    <!-- Datatables -->
    <script src="{% static "assets/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/datatables/js/dataTables.bootstrap.min.js" %}"></script>

    <script>
        $(document).ready(function () {
            var menu_type = '{{ menu_type }}' ;
            $('#dynamic-table').dataTable({
                "order": [[ 1, "asc" ]],
                "serverSide": true,
                "scrollX": true,
                stateSave: true,
                "ajax": {
                    "url": "{% url 'TransMethod__asJson' %}"
                },
                "columns": [
                    {"data": "code"},
                    {"data": "name"},
                    {"data": "update_date"},
                    {% if 'transactions.change_transactionmethod' in user.get_all_permissions %}
                        {
                            "className": 'text-center',
                            "orderable": false,
                            "data": null,
                            "render": function (data, type, full, meta) {
                                var button_edit = '<a href=../edit/' + full.id +'/'+menu_type+' class="fa fa-pencil fa-lg btn btn-primary btn-sm"></a>'
                                return button_edit;
                            }
                        }
                    {% endif %}
                ]
            });
        });
    </script>
{% endblock %}

src/ikari/transactions/templates/trans-type-list.html
{% extends "base.html" %}

<!--dynamic table-->
{% block extrahead %}
    {% load staticfiles %}
{% endblock %}

{% block title %}Transaction Type List{% endblock %}
{% block trans_type_active %}active{% endblock %}
{% block account_setting_a_active %}active{% endblock %}
{% block account_setting_i_active %}active{% endblock %}
{% block parent_accounting_a_active %}active{% endblock %}
{% block parent_accounting_i_active %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading" style="font-size: 20px">
                    Transaction Type List
                    <span class="tools pull-right">
                         {% if 'transactions.add_transactiontype' in user.get_all_permissions %}
                             <a class="btn btn-success start" href="{% url 'trans_type_add' %}">
                                 <i class="glyphicon glyphicon-plus"></i>
                                 <span>Add new</span>
                             </a>
                         {% endif %}
                    </span>
                </header>
                <div class="panel-body">
                    <div class="adv-table">
                        <table class="display table table-bordered table-striped"
                               id="dynamic-table" style="width:100%">
                            <thead>
                            <tr>
                                <th class="text-center">Update Date</th>
                                <th>Name</th>
                                <th class="text-center">Accountable</th>
                                {% if 'transactions.change_transactiontype' in user.get_all_permissions %}
                                    <th class="text-center">Edit</th>
                                {% endif %}
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}
{% block extrafoot %}
    {% load staticfiles %}
    <script src="{% static "assets/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/datatables/js/dataTables.bootstrap.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            $('#dynamic-table').dataTable({
                "order": [[0, "desc"]],
                "serverSide": true,
                "scrollX": true,
                stateSave: true,
                "ajax": {
                    "url": "{% url 'TransType__asJson' %}"
                },
                "columns": [
                    {"data": "update_date"},
                    {"data": "name"},
                    {
                        "orderable": false,
                        "data": null,
                        "render": function (data, type, full, meta) {
                            if (full.is_accountable == 'True') {
                                var mSpan = '<span class="label label-success label-mini">True</span>'
                                return mSpan
                            }
                            else {
                                var mSpan = '<span class="label label-danger label-mini">False</span>'
                                return mSpan
                            }
                        }
                    },
                    {% if 'transactions.change_transactiontype' in user.get_all_permissions %}
                        {
                            "orderable": false,
                            "data": null,
                            "render": function (data, type, full, meta) {
                                var button_edit = '<a href=../edit/' + full.id + '/false/ class="fa fa-pencil btn btn-primary btn-xs"></a>'
                                return button_edit;
                            }
                        }
                    {% endif %}
                ]
            });
        });
    </script>
{% endblock %}