src/ikari/banks/urls.py
from django.conf.urls import url
from banks import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='bank_list'),
    url(r'^add/$', views.bank_add, name='bank_add'),
    url(r'^edit/(?P<bank_id>\d+)/$', views.bank_edit, name='bank_edit'),
    url(r'^delete/(?P<bank_id>.*)/$', views.bank_delete, name='bank_delete'),
    url(r'^list/paging$', views.Bank__asJson, name='Bank__asJson'),
    url(r'^account_list/$', views.AccountList__asJson, name='Bank__AccountList__asJson'),
    url(r'^load_account/$', views.load_account, name='load_account'),
]

src/ikari/customers/urls.py
from django.conf.urls import url
from customers import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='customer_list'),
    url(r'^acc_customer_list/$', views.acc_customer_list, name='acc_customer_list'),
    url(r'^add/$', views.customer_add, name='customer_add'),
    url(r'^edit/(?P<customer_id>\d+)/$', views.customer_edit, name='customer_edit'),
    url(r'^get_by_pk/(?P<customer_id>.*)/(?P<rate_date>.*)/$', views.customer_By_pk, name='customer_By_pk'),
    url(r'^get_by_code/(?P<customer_code>.*)/$', views.customer_By_code, name='customer_By_code'),
    url(r'^acc_customer_add/$', views.acc_customer_add, name='acc_customer_add'),
    url(r'^acc_customer_edit/(?P<customer_id>\d+)/$', views.acc_customer_edit, name='acc_customer_edit'),
    url(r'^delete/(?P<customer_id>\d+)/$', views.customer_delete, name='customer_delete'),

    url(r'^delivery_add/$', views.delivery_add, name='delivery_add'),
    url(r'^delivery_edit/(?P<delivery_id>\d+)/$', views.delivery_edit, name='delivery_edit'),
    url(r'^delivery_edit/(?P<delivery_id>\d+)/(?P<active_tab_index>\d+)/pagination$', views.DeliveryContact__asJson,
        name='DeliveryContact__asJson'),
    url(r'^delivery_delete/(?P<delivery_id>\d+)/$', views.delivery_delete, name='delivery_delete'),
    url(r'^delivery_list/$', views.delivery_list, name='delivery_list'),
    url(r'^delivery_list/pagination$', views.DeliveryList__asJson, name='DeliveryList__asJson'),

    url(r'^item_add/(?P<customer_id>\d+)/$', views.item_add, name='customer_add_item'),
    url(r'^item_edit/(?P<custitem_id>\d+)/$', views.item_edit, name='customer_edit_item'),
    url(r'^item_delete/(?P<custitem_id>\d+)/$', views.item_delete, name='customer_delete_item'),
    url(r'^list/pagination$', views.CustomerList__asJson, name='CustomerList__asJson'),
    url(r'^item_add/(?P<customer_id>.*)/pagination$', views.CustomerItemList__asJson, name='CustomerItemList__asJson'),

    url(r'^edit/(?P<custitem_id>.*)/pagination$', views.CustomerEditItemList__asJson,
        name='CustomerEditItemList__asJson'),
    url(r'^item_add/getiteminfo$', views.get_item_info, name='get_item_info'),

    url(r'^get_customer_code_list/$', views.get_customer_code_list, name='get_customer_code_list'),
    url(r'^load_account_set/$', views.load_account_set, name='load_account_set'),
    url(r'^load_payment_code/$', views.load_payment_code, name='load_payment_code'),
    url(r'^load_tax_code/$', views.load_tax_code, name='load_tax_code'),
    url(r'^load_currency_code/$', views.load_currency_code, name='load_currency_code'),
    url(r'^account_list/$', views.AccountList__asJson, name='Customer__AccountList__asJson'),
    url(r'^account_set_list/$', views.AR_AccountSetList__asJson, name='Customer__AccountSetList__asJson'),
    url(r'^acc_customer_list/pagination$', views.AccCustomerList__asJson, name='Customer_AccCustomerList__asJson'),
    url(r'^currency_set_list/$', views.CurrencySetList__asJson, name='Customer__CurrencySetList__asJson'),
    url(r'^payment_code_set_list/$', views.PaymentModeSetList__asJson, name='Customer__PaymentModeSetList__asJson'),
    url(r'^tax_set_list/$', views.TaxSetList__asJson, name='Customer__TaxSetList__asJson'),
    url(r'^location_set_list/$', views.LocationSetList__asJson, name='Customer__LocationSetList__asJson'),
]

src/ikari/customers/models.py
from django.db import models
from companies.models import Company
from currencies.models import Currency
from countries.models import Country
from taxes.models import Tax
from transactions.models import TransactionMethod
from locations.models import Location
from accounts.models import Account, AccountSet, DistributionCode
from datetime import date
from items.models import Item
from utilities.constants import CUSTOMER_DEFAULT_MSG


# Create your models here.
class Customer(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    code = models.CharField(max_length=20, null=True, db_index=True)
    postal_code = models.CharField(max_length=20, null=True)
    address = models.TextField(null=True)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    tax = models.ForeignKey(Tax, on_delete=models.CASCADE, null=True)
    payment_mode = models.ForeignKey(TransactionMethod, on_delete=models.CASCADE, null=True)
    payment_code = models.ForeignKey('accounting.PaymentCode', on_delete=models.CASCADE, null=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True)
    credit_limit = models.DecimalField(max_digits=20, decimal_places=6, null=True, default=0)
    payment_term = models.CharField(max_length=10, null=True)
    account_set = models.ForeignKey(AccountSet, on_delete=models.CASCADE, null=True, related_name='account_set')
    account_receivable = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    interest_profile = models.ForeignKey(AccountSet, on_delete=models.CASCADE, null=True, related_name='interest_profile')
    phone = models.CharField(max_length=20, null=True)
    email = models.EmailField(null=True)
    fax = models.CharField(max_length=20, null=True)
    note1 = models.TextField(null=True)
    note2 = models.TextField(null=True)
    note3 = models.TextField(null=True)
    customer_type = models.IntegerField(null=True, default=0)
    pricing_type = models.CharField(max_length=10, null=True, default=0)
    interest_flag = models.CharField(max_length=10, null=True, default=0)
    statement = models.CharField(max_length=10, null=True, default=0)
    interest_1 = models.DecimalField(max_digits=20, decimal_places=6, null=True, default=0)
    interest_2 = models.DecimalField(max_digits=20, decimal_places=6, null=True, default=0)
    interest_3 = models.DecimalField(max_digits=20, decimal_places=6, null=True, default=0)
    interest_4 = models.DecimalField(max_digits=20, decimal_places=6, null=True, default=0)
    interest_5 = models.DecimalField(max_digits=20, decimal_places=6, null=True, default=0)
    accode_ar = models.CharField(max_length=20, null=True, default=0)
    accode_sal = models.CharField(max_length=20, null=True, default=0)
    accode_exc = models.CharField(max_length=20, null=True, default=0)
    accode_int = models.CharField(max_length=20, null=True, default=0)
    accode_bnk = models.CharField(max_length=20, null=True, default=0)
    accode_chr = models.CharField(max_length=20, null=True, default=0)
    center_ar = models.CharField(max_length=20, null=True, default=0)
    center_sal = models.CharField(max_length=20, null=True, default=0)
    center_exc = models.CharField(max_length=20, null=True, default=0)
    center_int = models.CharField(max_length=20, null=True, default=0)
    center_bnk = models.CharField(max_length=20, null=True, default=0)
    center_chr = models.CharField(max_length=20, null=True, default=0)
    is_active = models.BooleanField(default=True)
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()
    distribution_code = models.ForeignKey(DistributionCode, on_delete=models.CASCADE, null=True)
    email_msg = models.CharField(max_length=1000, null=True, default=CUSTOMER_DEFAULT_MSG)

# add dependency between customer with item as in new requirement


class CustomerItem(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    sales_price = models.DecimalField(max_digits=20, decimal_places=6, null=True)
    new_price = models.DecimalField(max_digits=20, decimal_places=6, null=True)
    leading_days = models.CharField(max_length=500, null=True)
    effective_date = models.DateField(null=True)
    is_active = models.BooleanField(default=True)
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()


class Delivery(models.Model):
    code = models.CharField(max_length=20, null=True)
    name = models.CharField(max_length=100)
    attention = models.CharField(max_length=500, null=True)
    phone = models.CharField(max_length=20, null=True)
    email = models.EmailField(max_length=50, null=True)
    fax = models.CharField(max_length=20, null=True)
    note_1 = models.CharField(max_length=4000, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=500, null=True)
    is_active = models.BooleanField(default=True)
    create_date = models.DateField(default=date.today)
    update_date = models.DateField(default=date.today)
    update_by = models.CharField(max_length=50, null=True)
    is_hidden = models.BooleanField()

src/ikari/customers/templates/acc-customer-list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Customer List{% endblock %}
{% block ar_customer_active %}active{% endblock %}
{% block parent_accounting_a_active %}active{% endblock %}
{% block parent_accounting_i_active %}active{% endblock %}
{% block parent_AR_a_active %}active{% endblock %}
{% block parent_AR_i_active %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading" style="font-size: 20px">
                    Customer List
                    <span class="tools pull-right">
                        {% if request.session.staff_admin %}
                            <a class="btn btn-success start" href="{% url 'acc_customer_add' %}">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Add new</span>
                            </a>
                        {% endif %}
                    </span>
                </header>
                <div class="panel-body">
                    <div class="adv-table">
                        <table class="display table table-bordered table-striped table-condensed"
                               id="custom-table" style="width:100%">
                            <thead>
                            <tr>
                                <th>Update Date</th>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Account Set</th>
                                <th>Payment Code</th>
                                <th>Currency Code</th>
                                <th>Tax Code</th>
                                <!-- <th class="text-center">Active</th> -->
                                {% if request.session.staff_admin %}
                                    <th class="text-center">Edit</th>
                                {% endif %}
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block js %}
    <!-- Datatables -->
    <script src="{% static "assets/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/datatables/js/dataTables.bootstrap.min.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#custom-table').dataTable({
                "order": [[1, "asc"]],
                "serverSide": true,
                "scrollX": true,
                stateSave: true,
                "ajax": {
                    "url": "{% url 'Customer_AccCustomerList__asJson' %}"
                },
                "columns": [
                    {"data": "update_date"},
                    {"data": "customer_code"},
                    {"data": "customer_name"},
                    {"data": "account_set"},
                    {"data": "payment_code"},
                    {"data": "currency_code"},
                    {"data": "tax_code"},
                    // {
                    //     "orderable": false,
                    //     "data": null,
                    //     "render": function (data, type, full, meta) {
                    //         if (full.is_active == 'True') {
                    //             var mSpan = '<span class="label label-success label-mini">True</span>'
                    //             return mSpan
                    //         }
                    //         else {
                    //             var mSpan = '<span class="label label-danger label-mini">False</span>'
                    //             return mSpan
                    //         }
                    //     }
                    // },
                    {% if request.session.staff_admin %}
                        {
                            "className": "text-center",
                            "orderable": false,
                            "data": null,
                            "render": function (data, type, full, meta) {
                                // var button_edit = '<a href="../edit/' + full.id + '/0/" class="fa fa-pencil btn btn-primary
                                var button_edit = '<a href="../acc_customer_edit/' + full.id + '/" class="fa fa-pencil fa-lg btn btn-primary btn-sm"></a>'
                                return button_edit;
                            }
                        }
                    {% endif %}
                ]
            });
        });
    </script>
{% endblock %}

src/ikari/customers/templates/customer-list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Customer List{% endblock %}
{% block customer_active %}active{% endblock %}
{% block customer_a_active %}active{% endblock %}
{% block customer_i_active %}active{% endblock %}
{% block sp_setting_a_active %}active{% endblock %}
{% block sp_setting_i_active %}active{% endblock %}
{% block parent_order_a_active %}active{% endblock %}
{% block parent_order_i_active %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading" style="font-size: 20px">
                    Customer List
                    <span class="tools pull-right">
                        {% if request.session.staff_admin %}
                            <a class="btn btn-success start" href="{% url 'customer_add' %}">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Add new</span>
                            </a>
                        {% endif %}
                    </span>
                </header>
                <div class="panel-body">
                    <div class="adv-table">
                        <table class="display table table-bordered table-striped table-condensed"
                               id="custom-table" style="width:100%">
                            <thead>
                            <tr>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Country</th>
                                {% if request.session.use_inventory %}
                                    <th>Location</th>
                                {% endif %}
                                <th>Currency</th>
                                <th>Tax</th>
                                <th>Last Update</th>
                                <!-- <th class="text-center">Active</th> -->
                                {% if request.session.staff_admin %}
                                    <th class="text-center">Edit</th>
                                {% endif %}
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block js %}
    <!-- Datatables -->
    <script src="{% static "assets/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/datatables/js/dataTables.bootstrap.min.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#custom-table').dataTable({
                "order": [[1, "asc"]],
                "serverSide": true,
                "scrollX": true,
                stateSave: true,
                "ajax": {
                    "url": "{% url 'CustomerList__asJson' %}"
                },
                "columns": [
                    {"data": "customer_code"},
                    {"data": "customer_name"},
                    {"data": "country_code"},
                    {% if request.session.use_inventory %}
                        {"data": "location_code"},
                    {% endif %}
                    {"data": "currency_code"},
                    {"data": "tax_name"},
                    {"data": "update_date"},
                    {% if request.session.staff_admin %}
                        {
                            "className": "text-center",
                            "orderable": false,
                            "data": null,
                            "render": function (data, type, full, meta) {
                                // var button_edit = '<a href="../edit/' + full.id + '/0/" class="fa fa-pencil btn btn-primary
                                var button_edit = '<a href="../edit/' + full.id + '/" class="fa fa-pencil fa-lg btn btn-primary btn-sm"></a>'
                                return button_edit;
                            }
                        }
                    {% endif %}
                ]
            });
        });
    </script>
{% endblock %}

src/ikari/customers/templates/delivery-form.html
{% extends "base.html" %}

{% block extrahead %}
    {% load staticfiles %}
{% endblock %}

{% block title %}
    {% if delivery.id %}
        Edit Delivery Info
    {% else %}
        Add Delivery Info
    {% endif %}
{% endblock %}
{% block delivery_active %}active{% endblock %}
{% block sp_setting_a_active %}active{% endblock %}
{% block sp_setting_i_active %}active{% endblock %}
{% block parent_order_a_active %}active{% endblock %}
{% block parent_order_i_active %}active{% endblock %}

{% block content %}
    <div id="content">
        {% if delivery.id %}
        {% comment %} 
            <ul id="tabs" class="nav nav-tabs" data-tabs="tabs"
                style="margin-left: 14px; margin-right: 24px;">
                <li {% if active_tab_index == '0' %} class="active"
                  {% else %}class=""
                  {% endif %}><a href="#delivery_tab" data-toggle="tab">Delivery</a></li>
                <li {% if active_tab_index == '1' %}class="active"
                  {% else %}class=""
                  {% endif %}><a href="#contact_tab" data-toggle="tab">Contacts</a></li>
            </ul>
            <div id="my-tab-content" class="tab-content">
            <div {% if active_tab_index == '0' %}
                class="tab-pane active"
            {% else %}
                class="tab-pane"
            {% endif %} id="delivery_tab">
        {% endcomment %}
        {% endif %}
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading" style="font-size: 20px">
                {% if delivery.id %}
                    Edit Delivery
                {% else %}
                    Add Delivery
                {% endif %}
                </header>
                <div class="panel-body">
                    <form class="form-horizontal"
                          {% if delivery.id %}action="{% url 'delivery_edit' delivery.id %}"
                          {% else %}action="{% url 'delivery_add' %}"{% endif %}
                        role="form" method="post" onsubmit="return checkForm(this);" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="code" class="col-lg-2 col-sm-2 control-label">Code<span
                                    class="span-required">(*)</span></label>
                            <div class="col-lg-4">
                                {{ form.code }}
                                <span class="messages">{{ form.errors.code }}</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name" class="col-lg-2 col-sm-2 control-label">Delivery To<span
                                    class="span-required">(*)</span></label>
                            <div class="col-lg-4">
                                {{ form.name|default_if_none:"" }}
                                <span class="messages">{{ form.errors.name }}</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address" class="col-lg-2 col-sm-2 control-label">Address</label>
                            <div class="col-lg-4">
                                {{ form.address|default_if_none:"" }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="note1" class="col-lg-2 col-sm-2 control-label">Attention</label>
                            <div class="col-lg-4">
                                {{ form.attention|default_if_none:"" }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="phone" class="col-lg-2 col-sm-2 control-label">Tel no.</label>
                            <div class="col-lg-4">
                                {{ form.phone|default_if_none:"" }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="remark" class="col-lg-2 col-sm-2 control-label">Remark</label>
                            <div class="col-lg-4">
                                {{ form.note_1|default_if_none:"" }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="last_update" class="col-lg-2 col-sm-2 control-label">Last Update</label>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="last_update" name="last_update"
                                {% if delivery.update_date %}
                                    value="{{ last_update }}"
                                {% else %}
                                    value=""
                                {% endif %}
                                disabled="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button type="submit" name="btnSave" class="btn btn-success">Save</button>
                                {% if 'customers.delete_delivery' in user.get_all_permissions and delivery.id %}
                                    <a href="#delete-dialog" data-toggle="modal" class="btn btn-danger">Delete</a>
                                {% endif %}
                                <a class="btn btn-default" href="{% url 'delivery_list' %}">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="delete-dialog"
         class="modal fade">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 class="modal-title">Delete Confirm Dialog</h4>
                </div>
                {% if delivery.id %}
                    <div class="modal-body">
                        <form role="form" action="{% url 'delivery_delete' delivery.id %}"
                              method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="exampleInputEmail1">Are you sure want to delete?</label>
                            </div>
                            <button type="submit" class="btn btn-success">OK</button>
                            <a class="btn btn-default" href="{% url 'delivery_list' %}">Cancel</a>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block extrafoot %}
    {% load staticfiles %}
    <script type="application/javascript" src="{% static 'js/ga.js' %}?{% now 'H' %}"></script>
    <script src="{% static "assets/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/datatables/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "js/select2/select2.js" %}"></script>

    <script>
        var deliver_id = '{{ delivery.id }}'
        $(document).ready(function () {
            if (deliver_id){
              $('#id_code').attr('tabindex', "-1");
              $('#id_name').focus();
            } else {
                $('#id_code').focus();
            }
        });
    </script>
{% endblock %}

src/ikari/customers/templates/delivery-list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Delivery List{% endblock %}
{% block delivery_active %}active{% endblock %}
{% block sp_setting_a_active %}active{% endblock %}
{% block sp_setting_i_active %}active{% endblock %}
{% block parent_order_a_active %}active{% endblock %}
{% block parent_order_i_active %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading" style="font-size: 20px">
                    Delivery List
                    <span class="tools pull-right">
                        {% if 'customers.add_delivery' in user.get_all_permissions %}
                            <a class="btn btn-success start" href="{% url 'delivery_add' %}">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Add new</span>
                            </a>
                        {% endif %}
                    </span>
                </header>
                     <div class="panel-body">
                        <div class="adv-table">
                            <table class="display table table-bordered table-striped table-condensed"
                                   id="custom-table" style="width:100%">
                                <thead>
                                <tr>
                                    <th>Update Date</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Phone</th>
                                    {% if 'customers.add_delivery' in user.get_all_permissions %}
                                        <th class="text-center">Edit</th>
                                    {% endif %}
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
            </section>
        </div>
    </div>
{% endblock %}
{% block js %}
    <!-- Datatables -->
    <script src="{% static "assets/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "assets/datatables/js/dataTables.bootstrap.min.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#custom-table').dataTable({
                "order": [[ 1, "asc" ]],
                "serverSide": true,
                "scrollX": true,
                stateSave: true,
                "ajax": {
                    "url": "{% url 'DeliveryList__asJson' %}"
                },
                "columns": [
                    {"data": "update_date"},
                    {"data": "delivery_code"},
                    {"data": "delivery_name"},
                    {"data": "delivery_address"},
                    {"data": "delivery_phone"},
                    {% if 'customers.add_delivery' in user.get_all_permissions %}
                    {
                        "className": "text-center",
                        "orderable": false,
                        "data": null,
                        "render": function (data, type, full, meta) {
                            var button_edit = '<a href="../delivery_edit/' + full.id + '" class="fa fa-pencil fa-lg btn btn-primary btn-sm"></a>'
                            return button_edit;
                        }
                    }
                    {% endif %}
                ]
            });
        });
    </script>
{% endblock %}